name: autorun

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
    

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run script on remote server
      run: ssh -o StrictHostKeyChecking=no nickng@s3.serv00.com "/home/nickng/run.sh" 
